### ISSUE TITLE
Problem with link results analyzer

### ISSUE THREAD

**Issue by Leobouloc** [entrepreneur-interet-general/the-magical-csv-merge-machine#77]
```13:12:27 low: api_queued_modules._link_results_analyzer('8b137e4f2bee9263e5e8dc4ad64cd3c9', {'module_name': 'es_linker', 'file_name': 'test_labo_hal_safe.csv'}, None) (8b137e4f2bee9263e5e8dc4ad64cd3c9_link_results_analyzer)
13:12:28 ValueError: could not convert string to float: 'Structure Inactive'
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1197, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m75380/.local/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/home/m75380/.local/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/m75380/.local/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/m75380/Documents/eig/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 419, in _link_results_analyzer
    result = proj.analyze_results(module_params)
  File "/home/m75380/Documents/eig/the-magical-csv-merge-machine/merge_machine/linker.py", line 485, in analyze_results
    for data in self.mem_data:
  File "/home/m75380/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1042, in __next__
    return self.get_chunk()
  File "/home/m75380/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1106, in get_chunk
    return self.read(nrows=size)
  File "/home/m75380/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "/home/m75380/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 936, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 1001, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1130, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1203, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: 'Structure Inactive'
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1197, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'```

**Comment by Leobouloc** [comment]
Fixed by:
https://github.com/entrepreneur-interet-general/Merge-Machine/commit/ac5c0b015d2791be80719b75f6a2d8d06420f463
