### ISSUE TITLE
Analyze de résultats: bug

### ISSUE THREAD

**Issue by Leobouloc** [entrepreneur-interet-general/the-magical-csv-merge-machine#82]
```
Traceback (most recent call last):
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/root/magical_laundry/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 419, in _link_results_analyzer
    result = proj.analyze_results(module_params)
  File "/root/magical_laundry/the-magical-csv-merge-machine/merge_machine/linker.py", line 478, in analyze_results
    for data in self.mem_data:
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 978, in __next__
    return self.get_chunk()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 1042, in get_chunk
    return self.read(nrows=size)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 1005, in read
    ret = self._engine.read(nrows)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 1748, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader.read (pandas/_libs/parsers.c:10862)
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory (pandas/_libs/parsers.c:11343)
  File "pandas/_libs/parsers.pyx", line 989, in pandas._libs.parsers.TextReader._read_rows (pandas/_libs/parsers.c:12175)
  File "pandas/_libs/parsers.pyx", line 1117, in pandas._libs.parsers.TextReader._convert_column_data (pandas/_libs/parsers.c:14136)
  File "pandas/_libs/parsers.pyx", line 1190, in pandas._libs.parsers.TextReader._convert_tokens (pandas/_libs/parsers.c:15330)
ValueError: could not convert string to float: 'Structure Inactive'
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1184, in pandas._libs.parsers.TextReader._convert_tokens (pandas/_libs/parsers.c:15254)
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/root/magical_laundry/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 419, in _link_results_analyzer
    result = proj.analyze_results(module_params)
  File "/root/magical_laundry/the-magical-csv-merge-machine/merge_machine/linker.py", line 478, in analyze_results
    for data in self.mem_data:
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 978, in __next__
    return self.get_chunk()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 1042, in get_chunk
    return self.read(nrows=size)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 1005, in read
    ret = self._engine.read(nrows)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/pandas/io/parsers.py", line 1748, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader.read (pandas/_libs/parsers.c:10862)
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory (pandas/_libs/parsers.c:11343)
  File "pandas/_libs/parsers.pyx", line 989, in pandas._libs.parsers.TextReader._read_rows (pandas/_libs/parsers.c:12175)
  File "pandas/_libs/parsers.pyx", line 1117, in pandas._libs.parsers.TextReader._convert_column_data (pandas/_libs/parsers.c:14136)
  File "pandas/_libs/parsers.pyx", line 1190, in pandas._libs.parsers.TextReader._convert_tokens (pandas/_libs/parsers.c:15330)
ValueError: could not convert string to float: 'Structure Inactive'
```

**Comment by Leobouloc** [comment]
Seems linked to variable column order in output. Check if fixed.
